# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ventura profana
tagline: Site da pastora ventura profana
email: venturaministerial@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Site da pastora ventura profana
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://profana.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: venturaprofana
#github_username:  jekyll

lang: pt-BR
timezone: America/Sao_Paulo
minima:
  skin: dark
  date_format: "%d/%m/%Y"
  # ícones do rodapé
  social_links:
    #facebook: venturaprofana
    instagram: venturaprofana
    #youtube_channel: 
    #youtube_channel_name: aprosmig
    #whatsapp: '+5561969696969'
    spotify: 5OtKmdYx2SsAzr6RjrwAip
    deezer: 76040832

# meta tags do jekyll-seo-tag
social:
  links:
    - https://www.facebook.com/aprosmig
    - https://www.instagram.com/venturaprofana
    - https://open.spotify.com/artist/5OtKmdYx2SsAzr6RjrwAip
    - https://deezer.page.link/76040832

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
